### ISSUE TITLE
How is the Dedukti standard developed?

### ISSUE THREAD

**Issue by 01mf02** [Deducteam/Dedukti-standard#1]
Hello! Let me start with some kind of a meta-issue: How is the development of the Dedukti standard to be done?

At the moment, we have a private repository with a TeX file in it.
This limits the amount of input to people who a) have access to the repository and b) can & want to run TeX to see a nice version of the proposal.
I believe that when developing a standard, it would be best to be as open as possible. That means removing as many obstacles as possible for a greater public to read and comment on the draft. (This, I believe, is *the* main strength of the Rust community, for example.) In particular, I would prefer having a) a public repository and b) the proposal developed as Markdown, so that it is easy to visualise even without access to TeX. (I, for example, had to search & install an additional TeX package in order to compile the draft.) We can easily render Markdown as PDF later using something like Pandoc.

The next question: Are we just supposed to edit the draft of the standard ad libitum? I, for one, am reluctant to do that, because I do not like to just replace something that somebody else wrote; also, if everyone just adds his/her two cents, then we will soon have a few €/$ of opinions lying around.
I would prefer just opening issues to discuss certain points, and to modify the standard once there is some consensus.

**Comment by fblanqui** [comment]
It is now public.

**Comment by francoisthire** [comment]
> The next question: Are we just supposed to edit the draft of the standard ad libitum? I, for one, am reluctant to do that, because I do not like to just replace something that somebody else wrote; also, if everyone just adds his/her two cents, then we will soon have a few €/$ of opinions lying around.
I would prefer just opening issues to discuss certain points, and to modify the standard once there is some consensus.

We can do as any open source project and submit PR. However, when there is no consensus on a point, I guess an issue or a PR can be opened. 

We are probably around 10 people involved, I don't think we need a strong process for modifications. Especially, no commitment is made from this TeX file for the moment, so any changes can be reverted easily.

**Comment by gabrielhdt** [comment]
I'm in favour of using a lightweight syntax (markdown, asciidoc, restructured text, you name it)

**Comment by 01mf02** [comment]
Thanks for all your comments!
